# Generated by Django 2.2.1 on 2019-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('availibility', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='customer.ProductCategory')),
            ],
        ),
    ]
